"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createStatus, updateStatus, deleteStatus } from "@/api/statuses";
import type { Status, Resource } from "@/lib/types";
import styles from "./StatusTable.module.scss";
import { Trash2, SquarePen } from "lucide-react";

interface StatusTableProps {
  resources: Resource[];
  statuses: Status[];
}

export default function StatusTable({ resources, statuses }: StatusTableProps) {
  const [editingStatus, setEditingStatus] = useState<Status | null>(null);
  const [newStatus, setNewStatus] = useState<{
    name: string;
  } | null>(null);

  const router = useRouter();

  async function handleSave(status: Status | null) {
    if (!status) return;

    const toUpdate = {
      name: status.name,
    };

    const updatedStatus = await updateStatus(status.id, toUpdate);
    if ("error" in updatedStatus) {
      alert(updatedStatus.error);
      return;
    }
    setEditingStatus(null);
    router.refresh();
  }

  async function handleAdd(draft: typeof newStatus) {
    if (!draft) return;

    const toCreate = {
      name: draft.name,
    };

    const createdStatus = await createStatus(toCreate);
    if ("error" in createdStatus) {
      alert(createdStatus.error);
      return;
    }
    setNewStatus(null);
    router.refresh();
  }

  async function handleDelete(statusId: number) {
    const confirmed = confirm("Are you sure you want to delete this status?");
    if (!confirmed) return;

    const deletedStatus = await deleteStatus(statusId);
    if ("error" in deletedStatus) {
      alert(`Error: ${deletedStatus.error}`);
      return;
    }
    router.refresh();
  }

  return (
    <section className={styles.statusTable}>
      <div className={styles.header}>
        <h1>Status Table</h1>
        <button
          className={styles.addButton}
          onClick={() => setNewStatus({ name: "" })}
        >
          Add Status
        </button>
      </div>
      <table className={styles.table}>
        <thead className={styles.tableHeaderRow}>
          <tr>
            <th className={styles.tableHeaderCell}>ID</th>
            <th className={styles.tableHeaderCell}>Name</th>
            <th className={styles.tableHeaderCell}>Resources</th>
            <th className={styles.tableHeaderCell}>Actions</th>
          </tr>
        </thead>
        <tbody className={styles.tableBody}>
          {newStatus && (
            <tr className={styles.tableRow}>
              <td className={styles.tableCell}>
                {/* ID will be generated by the backend */}
              </td>
              <td className={styles.tableCell}>
                <input
                  type="text"
                  value={newStatus.name}
                  onChange={(e) =>
                    setNewStatus({
                      ...newStatus,
                      name: e.target.value,
                    })
                  }
                />
              </td>
              <td className={styles.tableCell}>
                {/* Resources will be associated after creation */}
              </td>
              <td className={styles.tableCell}>
                <button
                  className={styles.saveButton}
                  onClick={() => handleAdd(newStatus)}
                >
                  Add
                </button>
                <button
                  className={styles.cancelButton}
                  onClick={() => setNewStatus(null)}
                >
                  Cancel
                </button>
              </td>
            </tr>
          )}
          {statuses
            .sort((a, b) => a.id - b.id)
            .map((status) => (
              <tr key={status.id} className={styles.tableRow}>
                <td className={styles.tableCell}>{status.id}</td>
                <td className={styles.tableCell}>
                  {editingStatus?.id === status.id ? (
                    <input
                      type="text"
                      value={editingStatus.name}
                      onChange={(e) =>
                        setEditingStatus({
                          ...editingStatus,
                          name: e.target.value,
                        })
                      }
                    />
                  ) : (
                    status.name
                  )}
                </td>
                <td className={styles.tableCell}>
                  {resources
                    .filter((resource) => resource.status?.id === status.id)
                    .map((resource) => resource.title)
                    .join(" | ")}
                </td>
                <td className={styles.tableCell}>
                  {editingStatus?.id === status.id ? (
                    <div className={styles.actionsRow}>
                      <button
                        className={styles.saveButton}
                        onClick={() => handleSave(editingStatus)}
                      >
                        Save
                      </button>
                      <button
                        className={styles.cancelButton}
                        onClick={() => setEditingStatus(null)}
                      >
                        Cancel
                      </button>
                    </div>
                  ) : (
                    <div className={styles.actionsRow}>
                      <button
                        className={styles.editButton}
                        onClick={() => setEditingStatus(status)}
                      >
                        <SquarePen className={styles.icon} />
                        Edit
                      </button>
                      <button
                        className={styles.deleteButton}
                        onClick={() => handleDelete(status.id)}
                      >
                        <Trash2 className={styles.icon} />
                        Delete
                      </button>
                    </div>
                  )}
                </td>
              </tr>
            ))}
        </tbody>
      </table>
    </section>
  );
}
