"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Type } from "../../../../lib/types";
import {
  createResource,
  updateResource,
  deleteResource,
} from "../../../../api/resources";
import type { Resource, Status, Category } from "../../../../lib/types";
import styles from "./ResourceTable.module.scss";
import ResourceCard from "../../../(site)/collections/[type]/ResourceGrid/ResourceCard/ResourceCard";
import { X, EllipsisVertical, SquarePen, Trash2 } from "lucide-react";

interface ResourceTableProps {
  resources: Resource[];
  statuses: Status[];
  categories: Category[];
}

export default function ResourceTable({
  resources,
  statuses,
  categories,
}: ResourceTableProps) {
  const [editingResource, setEditingResource] = useState<Resource | null>(null);
  const router = useRouter();

  const [newResource, setNewResource] = useState<{
    title: string;
    description: string;
    url: string;
    logo: string;
    type: Type;
    status?: Status;
    categories: Category[];
  } | null>(null);

  const [viewResource, setViewResource] = useState<Resource | null>(null);
  const [openMenuId, setOpenMenuId] = useState<number | null>(null);

  async function handleSave(resource: Resource | null) {
    if (!resource) return;

    const toUpdate = {
      title: resource.title,
      description: resource.description,
      url: resource.url,
      logo: resource.logo,
      statusId: resource.status?.id ?? null,
      categories: resource.categories.map((c) => c.id),
    };

    const updatedResource = await updateResource(resource.id, toUpdate);
    if ("error" in updatedResource) {
      alert(`Error: ${updatedResource.error}`);
      return;
    }

    setEditingResource(null);
    router.refresh();
  }

  async function handleAdd(draft: typeof newResource) {
    if (!draft) return;
    const toCreate = {
      title: draft.title,
      description: draft.description,
      url: draft.url,
      type: draft.type,
      logo: draft.logo,
      categories: draft.categories.map((c) => c.id),
      statusId: draft.status?.id,
    };

    const createdResource = await createResource(toCreate);
    if ("error" in createdResource) {
      alert(`Error: ${createdResource.error}`);
      return;
    }

    setNewResource(null);
    router.refresh();
  }

  async function handleDelete(resourceId: number) {
    const confirmed = confirm("Are you sure you want to delete this resource?");
    if (!confirmed) return;

    const deletedResource = await deleteResource(resourceId);
    if ("error" in deletedResource) {
      alert(`Error: ${deletedResource.error}`);
      return;
    }

    router.refresh();
  }

  return (
    <section className={styles.resourceTable}>
      <div className={styles.header}>
        <div>
          <h1>Resource Table</h1>
          <p className={styles.resourceCount}>
            <span className={styles.count}>{resources.length} resources</span>
          </p>
        </div>

        <button
          className={styles.addButton}
          onClick={() =>
            setNewResource({
              title: "",
              description: "",
              url: "",
              type: Type.Tools,
              logo: "",
              categories: [],
              status: undefined,
            })
          }
        >
          Add Resource
        </button>
      </div>

      {viewResource && (
        <div className={styles.viewModal}>
          <div className={styles.viewModalContent}>
            <button
              className={styles.closeButton}
              onClick={() => setViewResource(null)}
            >
              <X className={styles.icon} />
            </button>
            <ResourceCard resource={viewResource} />
          </div>
        </div>
      )}

      <table className={styles.table}>
        <thead className={styles.tableHeaderRow}>
          <tr className={styles.tableHeaderRow}>
            <th className={styles.tableHeaderCell}>ID</th>
            <th className={styles.tableHeaderCell}>Title</th>
            <th className={styles.tableHeaderCell}>Type</th>
            <th className={styles.tableHeaderCell}>Description</th>
            <th className={styles.tableHeaderCell}>URL</th>
            <th className={styles.tableHeaderCell}>Logo</th>
            <th className={styles.tableHeaderCell}>Status</th>
            <th className={styles.tableHeaderCell}>Categories</th>
            <th className={styles.tableHeaderCell}>Actions</th>
          </tr>
        </thead>
        <tbody className={styles.tableBody}>
          {newResource && (
            <tr>
              <td className={styles.tableCell}>
                {/* ID will be generated by the backend */}
              </td>
              <td className={styles.tableCell}>
                <input
                  type="text"
                  value={newResource.title}
                  onChange={(e) =>
                    setNewResource({
                      ...newResource,
                      title: e.target.value,
                    })
                  }
                />
              </td>
              <td className={styles.tableCell}>
                <select
                  value={newResource.type ?? ""}
                  onChange={(e) =>
                    setNewResource({
                      ...newResource,
                      type: e.target.value as Type,
                    })
                  }
                >
                  {Object.values(Type).map((type) => (
                    <option key={type} value={type}>
                      {type}
                    </option>
                  ))}
                </select>
              </td>
              <td className={styles.tableCell}>
                <input
                  type="text"
                  value={newResource.description}
                  onChange={(e) =>
                    setNewResource({
                      ...newResource,
                      description: e.target.value,
                    })
                  }
                />
              </td>
              <td className={styles.tableCell}>
                <input
                  type="text"
                  value={newResource.url}
                  onChange={(e) =>
                    setNewResource({
                      ...newResource,
                      url: e.target.value,
                    })
                  }
                />
              </td>
              <td className={styles.tableCell}>
                <input
                  type="text"
                  value={newResource.logo}
                  onChange={(e) =>
                    setNewResource({
                      ...newResource,
                      logo: e.target.value,
                    })
                  }
                />
              </td>
              <td className={styles.tableCell}>
                <select
                  value={newResource.status?.id ?? ""}
                  onChange={(e) => {
                    const selected = statuses.find(
                      (status) => status.id === Number(e.target.value),
                    );
                    setNewResource({
                      ...newResource,
                      status: selected,
                    });
                  }}
                >
                  <option value="">None</option>
                  {statuses.map((status) => (
                    <option key={status.id} value={status.id}>
                      {status.name}
                    </option>
                  ))}
                </select>
              </td>
              <td className={styles.tableCell}>
                <div>
                  {categories.map((category) => {
                    const isChecked = newResource.categories.some(
                      (c) => c.id === category.id,
                    );
                    return (
                      <label key={category.id}>
                        <input
                          type="checkbox"
                          checked={isChecked}
                          onChange={() => {
                            const updated = isChecked
                              ? newResource.categories.filter(
                                  (c) => c.id !== category.id,
                                )
                              : [...newResource.categories, category];
                            setNewResource({
                              ...newResource,
                              categories: updated,
                            });
                          }}
                        />
                        {category.name}
                      </label>
                    );
                  })}
                </div>
              </td>
              <td className={styles.tableCell}>
                <button onClick={() => handleAdd(newResource)}>Add</button>
                <button onClick={() => setNewResource(null)}>Cancel</button>
              </td>
            </tr>
          )}
          {resources
            .sort((a, b) => a.id - b.id)
            .map((resource) => (
              <tr key={resource.id} className={styles.tableRow}>
                <td className={styles.tableCell}>{resource.id}</td>
                <td className={styles.tableCell}>
                  {editingResource?.id === resource.id ? (
                    <input
                      type="text"
                      value={editingResource.title}
                      onChange={(e) =>
                        setEditingResource({
                          ...editingResource,
                          title: e.target.value,
                        })
                      }
                    />
                  ) : (
                    resource.title
                  )}
                </td>
                <td className={styles.tableCell}>{resource.type}</td>
                <td className={styles.tableCell}>
                  {editingResource?.id === resource.id ? (
                    <input
                      type="text"
                      value={editingResource.description}
                      onChange={(e) =>
                        setEditingResource({
                          ...editingResource,
                          description: e.target.value,
                        })
                      }
                    />
                  ) : (
                    resource.description
                  )}
                </td>
                <td className={styles.tableCell}>
                  {editingResource?.id === resource.id ? (
                    <input
                      type="text"
                      value={editingResource.url}
                      onChange={(e) =>
                        setEditingResource({
                          ...editingResource,
                          url: e.target.value,
                        })
                      }
                    />
                  ) : (
                    resource.url
                  )}
                </td>
                <td className={styles.tableCell}>
                  {editingResource?.id === resource.id ? (
                    <input
                      type="text"
                      value={editingResource.logo}
                      onChange={(e) =>
                        setEditingResource({
                          ...editingResource,
                          logo: e.target.value,
                        })
                      }
                    />
                  ) : (
                    resource.logo
                  )}
                </td>
                <td className={styles.tableCell}>
                  {editingResource?.id === resource.id ? (
                    <select
                      value={editingResource.status?.id ?? ""}
                      onChange={(e) => {
                        const selected = statuses.find(
                          (status) => status.id === Number(e.target.value),
                        );
                        setEditingResource({
                          ...editingResource,
                          status: selected,
                        });
                      }}
                    >
                      <option value="">None</option>
                      {statuses.map((status) => (
                        <option key={status.id} value={status.id}>
                          {status.name}
                        </option>
                      ))}
                    </select>
                  ) : (
                    resource.status?.name
                  )}
                </td>
                <td className={styles.tableCell}>
                  {editingResource?.id === resource.id ? (
                    <div>
                      {categories.map((category) => {
                        const isChecked = editingResource.categories.some(
                          (c) => c.id === category.id,
                        );
                        return (
                          <label key={category.id}>
                            <input
                              type="checkbox"
                              checked={isChecked}
                              onChange={() => {
                                const updated = isChecked
                                  ? editingResource.categories.filter(
                                      (c) => c.id !== category.id,
                                    )
                                  : [...editingResource.categories, category];
                                setEditingResource({
                                  ...editingResource,
                                  categories: updated,
                                });
                              }}
                            />
                            {category.name}
                          </label>
                        );
                      })}
                    </div>
                  ) : (
                    resource.categories.map((c) => c.name).join(" | ")
                  )}
                </td>
                <td className={styles.tableCell}>
                  <div className={styles.actionsRow}>
                    {editingResource?.id === resource.id ? (
                      <>
                        <button onClick={() => handleSave(editingResource)}>
                          Save
                        </button>
                        <button onClick={() => setEditingResource(null)}>
                          Cancel
                        </button>
                      </>
                    ) : (
                      <>
                        <button
                          className={styles.viewButton}
                          onClick={() => setViewResource(resource)}
                        >
                          View
                        </button>
                        <div className={styles.actionsWrapper}>
                          <button
                            className={styles.moreActionsButton}
                            onClick={() =>
                              setOpenMenuId(
                                openMenuId === resource.id ? null : resource.id,
                              )
                            }
                          >
                            <EllipsisVertical className={styles.icon} />
                          </button>
                          {openMenuId === resource.id && (
                            <div className={styles.actionsMenu}>
                              <button
                                className={styles.editButton}
                                onClick={() => {
                                  setEditingResource(resource);
                                  setOpenMenuId(null);
                                }}
                              >
                                <SquarePen className={styles.icon} />
                                Edit
                              </button>
                              <button
                                className={styles.deleteButton}
                                onClick={() => {
                                  handleDelete(resource.id);
                                  setOpenMenuId(null);
                                }}
                              >
                                <Trash2 className={styles.icon} />
                                Delete
                              </button>
                            </div>
                          )}
                        </div>
                      </>
                    )}
                  </div>
                </td>
              </tr>
            ))}
        </tbody>
      </table>
    </section>
  );
}
