export const categoryMeta: Record<string, { color: string }> = {
  Generators: { color: "#4a9d7a" },
  CSS: { color: "#6b8e4e" },
  Color: { color: "#b8923a" },
  Graphics: { color: "#a8674a" },
  Fonts: { color: "#7d8471" },
  Documentation: { color: "#8f7a5c" },
  UX: { color: "#3d8f8a" },
  UI: { color: "#5a7d8c" },
  Cheatsheets: { color: "#9c7450" },
  Components: { color: "#5e9c5e" },
  Animation: { color: "#b3572e" },
  JavaScript: { color: "#c4a23e" },
  APIs: { color: "#46748a" },
  Mobile: { color: "#6d7891" },
};
